apiVersion: batch/v1
kind: Job
metadata:
    name: transvirex-seed
    namespace: production
spec:
    ttlSecondsAfterFinished: 300
    backoffLimit: 3
    template:
        spec:
            restartPolicy: Never
            containers:
                - name: seed
                  image: ghcr.io/alecfoucher/transvirex-authentication-service:latest
                  command:
                      - sh
                      - -c
                      - >
                          node_modules/.bin/prisma db seed
                  env:
                      - name: POSTGRES_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: transvirex-config
                                key: POSTGRES_HOST
                      - name: POSTGRES_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: transvirex-config
                                key: POSTGRES_PORT
                      - name: POSTGRES_USER
                        valueFrom:
                            configMapKeyRef:
                                name: transvirex-config
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: transvirex-config
                                key: POSTGRES_PASSWORD
                      - name: POSTGRES_DB
                        valueFrom:
                            configMapKeyRef:
                                name: transvirex-config
                                key: POSTGRES_DB
