services:
    gateway-service:
        build:
            # Context set to the root of the backend monorepo
            context: ../../
            dockerfile: ./apps/gateway/Dockerfile
            target: development
        image: transvirex-gateway-service
        container_name: transvirex-gateway-service
        environment:
            - NODE_ENV=${NODE_ENV:-development}
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - DEBUG=${DEBUG:-*}
            - PORT=${GATEWAY_SERVICE_PORT:-3000}
            - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
            - POSTGRES_USER=${POSTGRES_USER:-postgres_user}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_password}
            - POSTGRES_DB=${POSTGRES_DB:-transvirex}
            - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
            - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
            - RABBITMQ_USER=${RABBITMQ_USER:-rabbitmq_user}
            - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-rabbitmq_password}
            - REDIS_HOST=${REDIS_HOST:-redis}
            - REDIS_PORT=${REDIS_PORT:-6379}
            - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_password}
            - REDIS_DB=${REDIS_DB:-0}
            - MONGODB_HOST=${MONGODB_HOST:-mongodb}
            - MONGODB_PORT=${MONGODB_PORT:-27017}
            - MONGODB_USER=${MONGODB_USER:-mongo_user}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD:-mongo_password}
            - MONGODB_DB=${MONGODB_DB:-transvirex}
            - JWT_SECRET=${JWT_SECRET}
            - AUTH_SERVICE_URL=http://authentication-service:3000
            - BILLING_SERVICE_URL=http://billing-service:3000
            - DELIVERY_SERVICE_URL=http://delivery-service:3000
            - STOCK_SERVICE_URL=http://stock-service:3000
            - USERS_SERVICE_URL=http://users-service:3000
        volumes:
            # - ./:/app/apps/gateway
            - /app/node_modules
        depends_on:
            - postgres
            - rabbitmq
            - redis
            - mongodb
        restart: unless-stopped
        networks:
            - transvirex-network
        develop:
            watch:
                - path: ./
                  ignore:
                      - node_modules
                      - dist
                  action: sync+restart
                  target: /app/apps/gateway
                - path: ../../libs/
                  ignore:
                      - node_modules
                      - dist
                  action: sync+restart
                  target: /app/libs
