allowBuilds:
  '@nestjs/core': true
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': true
  esbuild: true
  prisma: false
  unrs-resolver: true
confirmModulesPurge: false
minimumReleaseAge: 0
