apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-basic-auth
    namespace: production
type: Opaque
data:
    # admin:admin — généré avec htpasswd -nb admin admin
    users: YWRtaW46JGFwcjEkREtpcDhkL0EkcWhydkFqc1l1YkVSSGNYSFBxdVNLLw==
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: pgadmin-auth
    namespace: production
spec:
    basicAuth:
        secret: pgadmin-basic-auth
