apiVersion: apps/v1
kind: Deployment
metadata:
    name: pgadmin
    namespace: production
    labels:
        app: pgadmin
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pgadmin
    template:
        metadata:
            labels:
                app: pgadmin
        spec:
            containers:
                - name: pgadmin
                  image: dpage/pgadmin4:latest
                  env:
                      - name: PGADMIN_DEFAULT_EMAIL
                        valueFrom:
                            configMapKeyRef:
                                name: transvirex-config
                                key: PGADMIN_EMAIL
                      - name: PGADMIN_DEFAULT_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: transvirex-config
                                key: PGADMIN_PASSWORD
                  ports:
                      - containerPort: 80
                        name: http
                  resources:
                      requests:
                          cpu: 100m
                          memory: 128Mi
                      limits:
                          cpu: 300m
                          memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
    name: pgadmin
    namespace: production
    labels:
        app: pgadmin
spec:
    type: ClusterIP
    selector:
        app: pgadmin
    ports:
        - port: 80
          targetPort: 80
          name: http
          protocol: TCP
