apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: traefik-ingress-controller-role
rules:
    - apiGroups: ['']
      resources: ['services', 'endpoints', 'secrets']
      verbs: ['get', 'list', 'watch']
    - apiGroups: ['traefik.io']
      resources:
          [
              'ingressroutes',
              'ingressroutelines',
              'middlewares',
              'tlsoptions',
              'tlsstores',
              'traefikservices',
          ]
      verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: traefik-ingress-controller-binding
subjects:
    - kind: ServiceAccount
      name: transvirex-traefik-ingress-controller
      namespace: production
roleRef:
    kind: ClusterRole
    name: traefik-ingress-controller-role
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: transvirex-traefik-config
    namespace: production
    labels:
        app: traefik
data:
    traefik.yml: |
        entryPoints:
          web:
            address: ":80"
          websecure:
            address: ":443"
          traefik:
            address: ":9000"
          k8s-dashboard:
            address: ":8443"

        api:
          dashboard: true
          insecure: true

        providers:
          kubernetesCRD: {}

        log:
          level: INFO

        serversTransport:
          insecureSkipVerify: false

---
apiVersion: v1
kind: Service
metadata:
    name: transvirex-traefik
    namespace: production
    labels:
        app: traefik

spec:
    ports:
        - protocol: TCP
          name: web
          port: 80
        - protocol: TCP
          name: websecure
          port: 443
    type: LoadBalancer
    selector:
        app: traefik

---
apiVersion: v1
kind: ServiceAccount
metadata:
    namespace: production
    name: transvirex-traefik-ingress-controller

---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: production
    name: transvirex-traefik
    labels:
        app: traefik

spec:
    replicas: 1
    selector:
        matchLabels:
            app: traefik
    template:
        metadata:
            labels:
                app: traefik
        spec:
            serviceAccountName: transvirex-traefik-ingress-controller
            containers:
                - name: traefik
                  image: traefik:v2.10
                  imagePullPolicy: Always
                  volumeMounts:
                      - name: transvirex-traefik-config
                        mountPath: /etc/traefik/
                  ports:
                      - name: web
                        containerPort: 80
                      - name: websecure
                        containerPort: 443
            volumes:
                - name: transvirex-traefik-config
                  configMap:
                      name: transvirex-traefik-config
